// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTRQYCAH6t9mS8c1vK_NOWa0oGIix3rpc',
    appId: '1:1076670493168:web:d1a3fa68f5a9e392656d35',
    messagingSenderId: '1076670493168',
    projectId: 'disaster-watch-2c971',
    authDomain: 'disaster-watch-2c971.firebaseapp.com',
    storageBucket: 'disaster-watch-2c971.firebasestorage.app',
    measurementId: 'G-F9L871K3L9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAXhbuA1_Vakh5nF48XLxr9Zvta0K1Cx8',
    appId: '1:1076670493168:android:b4e3326e1e65e51b656d35',
    messagingSenderId: '1076670493168',
    projectId: 'disaster-watch-2c971',
    storageBucket: 'disaster-watch-2c971.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARzixhSYcFDPSONCJu3U4TTaZ93EWSm4Q',
    appId: '1:1076670493168:ios:03ad10ce35f3cac0656d35',
    messagingSenderId: '1076670493168',
    projectId: 'disaster-watch-2c971',
    storageBucket: 'disaster-watch-2c971.firebasestorage.app',
    iosBundleId: 'com.example.disasterWatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARzixhSYcFDPSONCJu3U4TTaZ93EWSm4Q',
    appId: '1:1076670493168:ios:03ad10ce35f3cac0656d35',
    messagingSenderId: '1076670493168',
    projectId: 'disaster-watch-2c971',
    storageBucket: 'disaster-watch-2c971.firebasestorage.app',
    iosBundleId: 'com.example.disasterWatch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTRQYCAH6t9mS8c1vK_NOWa0oGIix3rpc',
    appId: '1:1076670493168:web:0b8d9d695d327f4e656d35',
    messagingSenderId: '1076670493168',
    projectId: 'disaster-watch-2c971',
    authDomain: 'disaster-watch-2c971.firebaseapp.com',
    storageBucket: 'disaster-watch-2c971.firebasestorage.app',
    measurementId: 'G-Q2E59G9L20',
  );
}
